version: '3'

services:
  node:
    image: yosmy/node
    container_name: mundorecarga_web_node
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    networks:
      - frontend
    working_dir: /app/
    environment:
      - HTTPS=false
    command: "npm start"

networks:
  frontend:
    external: true
