version: '3'

services:
  nginx:
    image: yosmy/nginx
    container_name: mundorecarga_web_nginx
    volumes:
      - ../build:/usr/share/nginx/html
      - ./nginx/default_prod.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
      - 443
    networks:
      - frontend
    environment:
      - VIRTUAL_HOST=www.mundorecarga.com,mundorecarga.com
      - LETSENCRYPT_HOST=www.mundorecarga.com,mundorecarga.com
      - LETSENCRYPT_EMAIL=contact@mundorecarga.com
    working_dir: /usr/share/nginx/html
    restart: always
  rendertron:
    image: yosmy/rendertron
    container_name: mundorecarga_web_rendertron
    expose:
      - 80
    networks:
      - frontend
    restart: always

networks:
  frontend:
    external: true

